package dbscript

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// RoleTimeouts are set on every login role as a backstop for sessions that bypass the runtime
// (psql, scripts); the runtime sets its own per transaction (foundations 03, "Roles").
var RoleTimeouts = [][2]string{
	{"statement_timeout", "30s"},
	{"idle_in_transaction_session_timeout", "60s"},
	{"lock_timeout", "5s"},
}

var psqlVar = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func ident(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }
func lit(s string) string   { return `'` + strings.ReplaceAll(s, `'`, `''`) + `'` }

// Render renders the idempotent setup script, run by psql as a superuser after the password
// variables are \set. Sections: databases; login roles and memberships (cluster-wide); per
// database the schemas, their owner, the runtime role's privileges.
func Render(plan Plan) (string, error) {
	var b strings.Builder
	b.WriteString("-- Generated by be-ops db-script from the project's configuration; idempotent.\n")
	b.WriteString("-- Run with psql as a superuser; \\set the password variables first (be-ops db-script --password-vars).\n\n")
	dbs := databases(plan)
	b.WriteString("-- 1. Databases\n")
	for _, db := range dbs {
		fmt.Fprintf(&b, "SELECT %s WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = %s)\\gexec\n", lit("CREATE DATABASE "+ident(db)), lit(db))
	}
	b.WriteString("\n-- 2. Login roles (cluster-wide)\n")
	for _, c := range plan.Components {
		fmt.Fprintf(&b, "-- %s: owner %s, runtime %s\n", c.ID, c.Owner, c.Runtime)
		for _, r := range []struct {
			role string
			pw   Secret
		}{{c.Owner, c.OwnerPw}, {c.Runtime, c.RuntimePw}} {
			if err := loginRole(&b, r.role, r.pw); err != nil {
				return "", fmt.Errorf("%s: %w", c.ID, err)
			}
		}
		fmt.Fprintf(&b, "DO $be$ BEGIN IF EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid = m.roleid JOIN pg_roles u ON u.oid = m.member"+
			" WHERE r.rolname = %s AND u.rolname = %s) THEN REVOKE %s FROM %s; END IF; END $be$;\n\n",
			lit(c.Owner), lit(c.Runtime), ident(c.Owner), ident(c.Runtime))
	}
	for _, s := range plan.Shells {
		fmt.Fprintf(&b, "-- shell %s: login %s, switches to its members' runtime roles only (PostgreSQL 16)\n", s.ID, s.Login)
		if err := loginRole(&b, s.Login, s.LoginPw); err != nil {
			return "", fmt.Errorf("%s: %w", s.ID, err)
		}
		for _, m := range s.Members {
			fmt.Fprintf(&b, "GRANT %s TO %s WITH INHERIT FALSE, SET TRUE;\n", ident(m), ident(s.Login))
		}
		b.WriteString("\n")
	}
	b.WriteString("-- 3. Schemas and privileges, per database\n")
	for _, db := range dbs {
		fmt.Fprintf(&b, "\\connect %s\n", ident(db))
		for _, c := range plan.Components {
			if c.Database == db {
				schema(&b, c)
			}
		}
	}
	return b.String(), nil
}

func databases(plan Plan) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range plan.Components {
		if !seen[c.Database] {
			seen[c.Database] = true
			out = append(out, c.Database)
		}
	}
	for _, s := range plan.Shells {
		if !seen[s.Database] {
			seen[s.Database] = true
			out = append(out, s.Database)
		}
	}
	sort.Strings(out)
	return out
}

func loginRole(b *strings.Builder, role string, pw Secret) error {
	if !psqlVar.MatchString(pw.Var) {
		return fmt.Errorf("password variable %q of role %q is not a psql variable name", pw.Var, role)
	}
	fmt.Fprintf(b, "DO $be$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %s) THEN CREATE ROLE %s LOGIN; END IF; END $be$;\n", lit(role), ident(role))
	fmt.Fprintf(b, "ALTER ROLE %s LOGIN PASSWORD :'%s';\n", ident(role), pw.Var)
	for _, t := range RoleTimeouts {
		fmt.Fprintf(b, "ALTER ROLE %s SET %s = %s;\n", ident(role), t[0], lit(t[1]))
	}
	return nil
}

func schema(b *strings.Builder, c Identity) {
	s, o, r := ident(c.Schema), ident(c.Owner), ident(c.Runtime)
	fmt.Fprintf(b, "-- %s\n", c.ID)
	fmt.Fprintf(b, "CREATE SCHEMA IF NOT EXISTS %s AUTHORIZATION %s;\n", s, o)
	fmt.Fprintf(b, "ALTER SCHEMA %s OWNER TO %s;\n", s, o)
	fmt.Fprintf(b, "REVOKE ALL ON SCHEMA %s FROM PUBLIC;\n", s)
	fmt.Fprintf(b, "GRANT USAGE ON SCHEMA %s TO %s;\n", s, r)
	fmt.Fprintf(b, "REVOKE CREATE ON SCHEMA %s FROM %s;\n", s, r)
	fmt.Fprintf(b, "ALTER DEFAULT PRIVILEGES FOR ROLE %s IN SCHEMA %s GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %s;\n", o, s, r)
	fmt.Fprintf(b, "ALTER DEFAULT PRIVILEGES FOR ROLE %s IN SCHEMA %s GRANT USAGE, SELECT ON SEQUENCES TO %s;\n", o, s, r)
	fmt.Fprintf(b, "ALTER DEFAULT PRIVILEGES FOR ROLE %s IN SCHEMA %s GRANT EXECUTE ON FUNCTIONS TO %s;\n", o, s, r)
	fmt.Fprintf(b, "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %s TO %s;\n", s, r)
	fmt.Fprintf(b, "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %s TO %s;\n\n", s, r)
}

// PasswordVars lists "<psql variable>\t<source>" for every login role, for db-init to \set.
func PasswordVars(plan Plan) []string {
	seen := map[string]bool{}
	var out []string
	add := func(s Secret) {
		if !seen[s.Var] {
			seen[s.Var] = true
			out = append(out, s.Var+"\t"+s.Source)
		}
	}
	for _, c := range plan.Components {
		add(c.OwnerPw)
		add(c.RuntimePw)
	}
	for _, s := range plan.Shells {
		add(s.LoginPw)
	}
	return out
}
