package edge

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Settings is the project's edge settings file (infra/edge.yaml, foundations 18 "Edge
// settings"): what is not per route.
type Settings struct {
	// Host is the edge host name: the Host() of every router on Docker, the Ingress hostname on
	// Kubernetes (required there). Empty on Docker routes by path only.
	Host string `yaml:"host"`
	// TLSSecret is the Kubernetes certificate Secret every entry sharing the host carries.
	TLSSecret string `yaml:"tlsSecret"`
	// EntryPoints are the Traefik entry points of every router; empty = all.
	EntryPoints []string `yaml:"entrypoints"`
	// Rate is the default per-client-IP rate of the be-edge chain.
	Rate struct {
		Average int `yaml:"average"`
		Burst   int `yaml:"burst"`
	} `yaml:"rate"`
	// IngressAnnotations go to the deploy file's k8s.ingressAnnotations (the shared middleware
	// chain of the cluster's controller); be-ops owns that field only when this is set.
	IngressAnnotations map[string]string `yaml:"ingressAnnotations"`
}

// LoadSettings reads the settings file; a missing file means the defaults.
func LoadSettings(path string) (Settings, error) {
	var s Settings
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return s, nil
	}
	if err != nil {
		return s, err
	}
	if err := yaml.Unmarshal(raw, &s); err != nil {
		return s, fmt.Errorf("%s: %w", path, err)
	}
	return s, nil
}

// strippedHeaders are the client-supplied headers the edge removes (foundations 18, "What the
// edge does to every request"): tracing and request ID, and every be-* header of the protocol.
var strippedHeaders = []string{"X-Request-Id", "baggage", "be-actor-act", "be-actor-sub", "be-caller", "traceparent", "tracestate"}

// MiddlewareFile renders infra/traefik/dynamic/edge.yml: the shared chain be-edge every router
// uses, for Traefik's file provider. It names no service, so it never goes stale on an upgrade.
func MiddlewareFile(s Settings) []byte {
	avg, burst := s.Rate.Average, s.Rate.Burst
	if avg == 0 {
		avg = 100
	}
	if burst == 0 {
		burst = 2 * avg
	}
	hs := append([]string(nil), strippedHeaders...)
	sort.Strings(hs)
	var b strings.Builder
	b.WriteString("# Generated by be-ops edge from infra/edge.yaml (foundations 18); do not edit.\n")
	b.WriteString("http:\n  middlewares:\n")
	b.WriteString("    be-edge:\n      chain:\n        middlewares: [be-edge-strip, be-edge-rate]\n")
	b.WriteString("    be-edge-strip:\n      headers:\n        customRequestHeaders:   # an empty value removes the header\n")
	for _, h := range hs {
		fmt.Fprintf(&b, "          %s: \"\"\n", h)
	}
	fmt.Fprintf(&b, "    be-edge-rate:\n      rateLimit:\n        average: %d\n        burst: %d\n", avg, burst)
	return []byte(b.String())
}
