package configschema

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/brickKit/be-ops/internal/component"
	"github.com/brickKit/be-ops/internal/protocol"
	"github.com/brickKit/be-ops/internal/yamlblock"
	"gopkg.in/yaml.v3"
)

const marker = "Protocol keys: generated by be-ops from be-protocol schemas/config-keys.yaml (P2.8); do not edit.\nProfiles: "

// Apply rewrites the configSchema block of a component.yaml: the protocol keys of the block
// first (in catalogue order), then the component's own keys as they were written; required lists
// the protocol keys the block needs, then the component's own required keys. Keys the catalogue
// knows (protocol or retired) are never kept from the old block. Every other top-level block of
// the file is left as written.
func Apply(c *component.Component, b Block) ([]byte, error) {
	cat, err := protocol.LoadCatalogue()
	if err != nil {
		return nil, err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(c.ManifestRaw, &doc); err != nil {
		return nil, fmt.Errorf("%s: %w", c.ManifestPath, err)
	}
	old := mapValue(doc.Content[0], "configSchema")
	cs := &yaml.Node{Kind: yaml.MappingNode}
	props, req := propsNode(cat, c, b), requiredNode(cat, c, b)
	wrote := map[string]bool{}
	if old != nil {
		for i := 0; i+1 < len(old.Content); i += 2 {
			k := old.Content[i]
			switch k.Value {
			case "properties":
				cs.Content = append(cs.Content, str("properties"), props)
			case "required":
				cs.Content = append(cs.Content, str("required"), req)
			default:
				cs.Content = append(cs.Content, k, old.Content[i+1])
			}
			wrote[k.Value] = true
		}
	}
	if !wrote["type"] {
		cs.Content = append([]*yaml.Node{str("type"), str("object")}, cs.Content...)
	}
	if !wrote["properties"] {
		cs.Content = append(cs.Content, str("properties"), props)
	}
	if !wrote["required"] && len(req.Content) > 0 {
		cs.Content = append(cs.Content, str("required"), req)
	}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{str("configSchema"), cs}}); err != nil {
		return nil, err
	}
	return yamlblock.ReplaceTopLevel(c.ManifestRaw, "configSchema", buf.String()), nil
}

func propsNode(cat *protocol.Catalogue, c *component.Component, b Block) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode}
	for i, p := range b.Props {
		k := str(p.Name)
		if i == 0 {
			k.HeadComment = marker + strings.Join(b.Profiles, ", ") + extra(b.OptIns) + b.Note
		}
		v := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle, Content: []*yaml.Node{str("type"), str(p.Type)}}
		if p.Default != nil {
			v.Content = append(v.Content, str("default"), &yaml.Node{Kind: yaml.ScalarNode, Tag: tagOf(p.Type), Value: *p.Default})
		}
		if p.Secret {
			v.Content = append(v.Content, str("secret"), &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
		}
		if p.Mount != "" {
			v.Content = append(v.Content, str("mount"), str(p.Mount))
		}
		if p.Comment != "" {
			v.LineComment = p.Comment
		}
		n.Content = append(n.Content, k, v)
	}
	for _, p := range c.Props {
		if !isCatalogueKey(cat, p.Name) {
			n.Content = append(n.Content, p.KeyNode, p.Node)
		}
	}
	if len(n.Content) == 0 {
		n.Style = yaml.FlowStyle
	}
	return n
}

func extra(optIns []string) string {
	if len(optIns) == 0 {
		return ""
	}
	return "; also " + strings.Join(optIns, ", ")
}

func requiredNode(cat *protocol.Catalogue, c *component.Component, b Block) *yaml.Node {
	n := &yaml.Node{Kind: yaml.SequenceNode}
	seen := map[string]bool{}
	for _, r := range b.Required {
		n.Content = append(n.Content, str(r))
		seen[r] = true
	}
	for _, r := range c.Required {
		if !seen[r] && !isCatalogueKey(cat, r) {
			n.Content = append(n.Content, str(r))
			seen[r] = true
		}
	}
	if len(n.Content) == 0 {
		n.Style = yaml.FlowStyle
	}
	return n
}

func tagOf(typ string) string {
	switch typ {
	case "integer":
		return "!!int"
	case "boolean":
		return "!!bool"
	case "number":
		return "!!float"
	}
	return "!!str"
}

func str(v string) *yaml.Node { return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v} }

func mapValue(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}
