// Package authzgen generates, per component, the constants for its permission keys and resource
// types and its authorization catalogue (keys with type and delegable; resource types with
// view_key, keys, relations, share, fields) as a source file of the component's language
// (authz-architecture §4.2): Go backend/internal/authzgen/authzgen.go, Python
// backend/app/authzgen.py, TypeScript src/authzgen.ts. Gate authzgen-fresh compares the file with
// a fresh render byte for byte.
package authzgen

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/brickKit/be-ops/internal/authzdecl"
	"github.com/brickKit/be-ops/internal/component"
)

// Lang is a target language.
type Lang string

const (
	Go         Lang = "go"
	Python     Lang = "python"
	TypeScript Lang = "ts"
)

// Options tune the rendering.
type Options struct {
	GoSDKImport string // default github.com/brickKit/be-sdk-go
}

const header = "Code generated by be-ops authzgen from assembly.yaml; DO NOT EDIT."

// KeyEntry is one key of the component's catalogue (contract-infra-authz catalog key_entry).
type KeyEntry struct {
	Key       string `json:"key"`
	Title     string `json:"title"`
	Type      string `json:"type"`
	Delegable *bool  `json:"delegable,omitempty"`
}

// Catalogue is what the runtime gets from the generated file.
type Catalogue struct {
	Component     string                  `json:"component"`
	Keys          []KeyEntry              `json:"keys"`
	ResourceTypes []authzdecl.CatalogType `json:"resource_types"`
}

type constant struct{ name, value, kind, comment string }

// model collects the constants and the catalogue of one component, refusing two constants with
// one name.
func model(c *component.Component, name func(string) string) ([]constant, Catalogue, error) {
	cat := Catalogue{Component: c.ID, Keys: []KeyEntry{}, ResourceTypes: authzdecl.CatalogTypes([]*component.Component{c})}
	if cat.ResourceTypes == nil {
		cat.ResourceTypes = []authzdecl.CatalogType{}
	}
	var consts []constant
	seen := map[string]string{}
	add := func(value, kind, comment string) error {
		n := name(value)
		if prev, ok := seen[n]; ok {
			return fmt.Errorf("%s: %s and %s both become the constant %s", c.ID, prev, value, n)
		}
		seen[n] = value
		consts = append(consts, constant{n, value, kind, comment})
		return nil
	}
	for _, p := range c.Assembly.Permissions {
		cat.Keys = append(cat.Keys, KeyEntry{Key: p.Key, Title: p.Title, Type: p.Type, Delegable: p.Delegable})
		if err := add(p.Key, "key", p.Type+": "+p.Title); err != nil {
			return nil, cat, err
		}
	}
	for _, r := range cat.ResourceTypes {
		if err := add(r.Type, "type", "table "+r.Table+", view_key "+r.ViewKey); err != nil {
			return nil, cat, err
		}
	}
	return consts, cat, nil
}

// Render renders the generated file of a component in a language.
func Render(c *component.Component, lang Lang, o Options) ([]byte, error) {
	switch lang {
	case Go:
		return renderGo(c, o)
	case Python:
		return renderPython(c)
	case TypeScript:
		return renderTS(c)
	}
	return nil, fmt.Errorf("unknown language %q", lang)
}

// GoName is the Go and TypeScript constant name: the segments after the domain, PascalCase
// (erp.sales.pricing.read -> SalesPricingRead).
func GoName(v string) string {
	var b strings.Builder
	for _, w := range words(v) {
		b.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	return b.String()
}

// PyName is the Python constant name: the segments after the domain, UPPER_SNAKE.
func PyName(v string) string {
	return strings.ToUpper(strings.Join(words(v), "_"))
}

func words(v string) []string {
	segs := strings.Split(v, ".")
	if len(segs) > 1 {
		segs = segs[1:]
	}
	var out []string
	for _, s := range segs {
		for _, w := range strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' }) {
			out = append(out, w)
		}
	}
	return out
}

func catalogueJSON(cat Catalogue, indent bool) (string, error) {
	var b []byte
	var err error
	if indent {
		b, err = json.MarshalIndent(cat, "", "  ")
	} else {
		b, err = json.Marshal(cat)
	}
	return string(b), err
}
