package authzgen

import (
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/brickKit/be-ops/internal/component"
	"github.com/brickKit/be-ops/internal/testfixture"
)

func widget(t *testing.T) *component.Component {
	t.Helper()
	c, err := component.Load(testfixture.Copy(t, "widget"))
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func TestNames_DropDomainAndCase(t *testing.T) {
	if got := GoName("erp.sales.pricing.read"); got != "SalesPricingRead" {
		t.Errorf("go name = %s", got)
	}
	if got := GoName("integration.im-dingtalk.send_now"); got != "ImDingtalkSendNow" {
		t.Errorf("go name = %s", got)
	}
	if got := PyName("erp.sales.pricing.read"); got != "SALES_PRICING_READ" {
		t.Errorf("py name = %s", got)
	}
}

func TestRender_GoIsValidAndTyped(t *testing.T) {
	src, err := Render(widget(t), Go, Options{})
	if err != nil {
		t.Fatal(err)
	}
	s := string(src)
	for _, want := range []string{
		"// Code generated by be-ops authzgen", "DO NOT EDIT.", "package authzgen",
		`besdk "github.com/brickKit/be-sdk-go"`,
		`"view_key": "conformance.widget.view"`, `"delegable": false`, `"set": "conformance.widget.price"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("Go output lacks %q:\n%s", want, s)
		}
	}
	for _, re := range []string{`WidgetView\s+besdk\.PermKey\s+= "conformance\.widget\.view"`,
		`WidgetPriceRead\s+besdk\.PermKey\s+= "conformance\.widget\.price\.read"`,
		`WidgetWidget\s+besdk\.ResourceType\s+= "conformance\.widget\.widget"`} {
		if !regexp.MustCompile(re).MatchString(s) {
			t.Errorf("Go output lacks %s (gofmt alignment allowed)", re)
		}
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "authzgen.go", src, 0); err != nil {
		t.Errorf("not valid Go: %v", err)
	}
	again, _ := Render(widget(t), Go, Options{})
	if string(again) != s {
		t.Error("not deterministic")
	}
}

func TestRender_Python(t *testing.T) {
	src, err := Render(widget(t), Python, Options{})
	if err != nil {
		t.Fatal(err)
	}
	s := string(src)
	for _, want := range []string{"# Code generated by be-ops authzgen", `WIDGET_VIEW: Final = "conformance.widget.view"`,
		`WIDGET_WIDGET: Final = "conformance.widget.widget"`, "CATALOG_JSON: Final = "} {
		if !strings.Contains(s, want) {
			t.Errorf("Python output lacks %q:\n%s", want, s)
		}
	}
	if py, err := exec.LookPath("python3"); err == nil {
		p := filepath.Join(t.TempDir(), "authzgen.py")
		os.WriteFile(p, src, 0o644)
		cmd := exec.Command(py, "-c", "import json,runpy; m=runpy.run_path('"+p+"'); json.loads(m['CATALOG_JSON'])['resource_types'][0]['view_key']")
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Errorf("python cannot load it: %v\n%s", err, out)
		}
	}
}

func TestRender_TypeScript(t *testing.T) {
	src, err := Render(widget(t), TypeScript, Options{})
	if err != nil {
		t.Fatal(err)
	}
	s := string(src)
	for _, want := range []string{"// Code generated by be-ops authzgen", `export const WidgetView = "conformance.widget.view" as const;`,
		`export const WidgetWidget = "conformance.widget.widget" as const;`, "export const catalog = {", "} as const;"} {
		if !strings.Contains(s, want) {
			t.Errorf("TS output lacks %q:\n%s", want, s)
		}
	}
}

func TestRender_NameCollisionIsRefused(t *testing.T) {
	c := widget(t)
	c.Assembly.Permissions = append(c.Assembly.Permissions, component.Permission{Key: "conformance.widget.widget", Type: "action"})
	if _, err := Render(c, Go, Options{}); err == nil {
		t.Error("a key and a type with one constant name must be refused")
	}
}

func TestDetect_LanguageAndDefaultPath(t *testing.T) {
	dir := t.TempDir()
	if _, _, err := Detect(dir); err == nil {
		t.Error("no language marker: want an error")
	}
	testfixture.Write(t, dir, "backend/go.mod", "module x\n")
	lang, path, err := Detect(dir)
	if err != nil || lang != Go || path != filepath.Join(dir, "backend/internal/authzgen/authzgen.go") {
		t.Errorf("go = %v %s %v", lang, path, err)
	}
	py := t.TempDir()
	testfixture.Write(t, py, "pyproject.toml", "")
	if lang, path, _ := Detect(py); lang != Python || path != filepath.Join(py, "backend/app/authzgen.py") {
		t.Errorf("python = %v %s", lang, path)
	}
	ts := t.TempDir()
	testfixture.Write(t, ts, "package.json", "{}")
	if lang, path, _ := Detect(ts); lang != TypeScript || path != filepath.Join(ts, "src/authzgen.ts") {
		t.Errorf("ts = %v %s", lang, path)
	}
	if lang, err := LangOf("x/authzgen.py"); err != nil || lang != Python {
		t.Errorf("LangOf .py = %v %v", lang, err)
	}
}
