// Package eventsdecl generates and checks the component.yaml `events:` block (be-protocol P12.16,
// brickKit ≥ v1.3.0): publishes = the subjects of the component's event contract except
// best-effort pokes; subscribes = events.consumes of its conformance fixtures. Gate
// events-declaration-scan runs Check.
package eventsdecl

import (
	"fmt"
	"strings"

	"github.com/brickKit/be-ops/internal/component"
	"github.com/brickKit/be-ops/internal/protocol"
	"github.com/brickKit/be-ops/internal/yamlblock"
)

// Decl is the generated events block.
type Decl struct {
	Publishes  []string
	Subscribes []string
	// Warnings are reported but do not fail generation (for example: no fixtures file, so the
	// subscriptions already declared are kept).
	Warnings []string
}

// Generate derives the block from the event contract and the fixtures.
func Generate(c *component.Component) (Decl, error) {
	re, err := protocol.SubjectPattern()
	if err != nil {
		return Decl{}, err
	}
	entries, err := c.EventContracts()
	if err != nil {
		return Decl{}, err
	}
	var d Decl
	seen := map[string]bool{}
	for _, e := range entries {
		if e.Signal || seen[e.Subject] {
			continue
		}
		if !re.MatchString(e.Subject) {
			return Decl{}, fmt.Errorf("%s: subject %q is not <domain>.<name>.<event…>.v<n> (P12.3)", e.File, e.Subject)
		}
		seen[e.Subject] = true
		d.Publishes = append(d.Publishes, e.Subject)
	}
	fx, err := c.Fixtures()
	if err != nil {
		return Decl{}, err
	}
	subs := fx.Consumes
	if !fx.Present {
		subs = c.Events.Subscribes
		if len(subs) > 0 {
			d.Warnings = append(d.Warnings, fmt.Sprintf("%s: no %s; the subscriptions already declared are kept", c.ID, c.FixturesPath()))
		}
	}
	seen = map[string]bool{}
	for _, s := range subs {
		if seen[s] {
			continue
		}
		if !validSubscription(s, re.MatchString) {
			return Decl{}, fmt.Errorf("%s: subscription %q is neither a subject (P12.3) nor a prefix ending in *", c.ID, s)
		}
		seen[s] = true
		d.Subscribes = append(d.Subscribes, s)
	}
	return d, nil
}

func validSubscription(s string, isSubject func(string) bool) bool {
	if p, ok := strings.CutSuffix(s, "*"); ok {
		return p == "" || !strings.Contains(p, "*")
	}
	return isSubject(s)
}

// Check compares the declared block with the generated one, as sets. It returns one line per
// difference; none means current.
func Check(c *component.Component, d Decl) []string {
	var out []string
	out = append(out, diff(c.ID, "events.publishes", c.Events.Publishes, d.Publishes)...)
	out = append(out, diff(c.ID, "events.subscribes", c.Events.Subscribes, d.Subscribes)...)
	return out
}

func diff(id, field string, have, want []string) []string {
	h, w := set(have), set(want)
	var out []string
	for _, s := range want {
		if !h[s] {
			out = append(out, fmt.Sprintf("%s: %s lacks %s", id, field, s))
		}
	}
	for _, s := range have {
		if !w[s] {
			out = append(out, fmt.Sprintf("%s: %s has %s, which the contract and fixtures do not", id, field, s))
		}
	}
	return out
}

func set(xs []string) map[string]bool {
	m := map[string]bool{}
	for _, x := range xs {
		m[x] = true
	}
	return m
}

// Render returns the block text; empty when the component neither publishes nor subscribes.
func Render(d Decl) string {
	if len(d.Publishes) == 0 && len(d.Subscribes) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("events:  # generated by be-ops from contracts/events and conformance/fixtures.yaml (P12.16); do not edit\n")
	writeList(&b, "publishes", d.Publishes)
	writeList(&b, "subscribes", d.Subscribes)
	return b.String()
}

func writeList(b *strings.Builder, key string, xs []string) {
	if len(xs) == 0 {
		return
	}
	fmt.Fprintf(b, "  %s:\n", key)
	for _, x := range xs {
		fmt.Fprintf(b, "    - %s\n", yamlScalar(x))
	}
}

// yamlScalar quotes a prefix subscription ending in *, which YAML would read as an alias.
func yamlScalar(s string) string {
	if strings.HasPrefix(s, "*") {
		return `"` + s + `"`
	}
	return s
}

// Apply rewrites the events block of a component.yaml.
func Apply(manifest []byte, d Decl) []byte {
	return yamlblock.ReplaceTopLevel(manifest, "events", Render(d))
}
