package eventsdecl

import (
	"reflect"
	"strings"
	"testing"

	"github.com/brickKit/be-ops/internal/component"
	"github.com/brickKit/be-ops/internal/testfixture"
)

func load(t *testing.T, dir string) *component.Component {
	t.Helper()
	c, err := component.Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func TestGenerate_WidgetFromContractAndFixtures(t *testing.T) {
	g, err := Generate(load(t, testfixture.Copy(t, "widget")))
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(g.Publishes, []string{"conformance.widget.created.v1", "conformance.widget.approved.v1", "conformance.widget.reverted.v1"}) {
		t.Errorf("publishes = %v", g.Publishes)
	}
	if !reflect.DeepEqual(g.Subscribes, []string{"conformance.owner.updated.v1", "conformance.reservation.expired.v1"}) {
		t.Errorf("subscribes = %v", g.Subscribes)
	}
}

func TestCheck_PublishedWidgetIsCurrent(t *testing.T) {
	c := load(t, testfixture.Copy(t, "widget"))
	g, err := Generate(c)
	if err != nil {
		t.Fatal(err)
	}
	if d := Check(c, g); len(d) != 0 {
		t.Errorf("widget events block should be current, got %v", d)
	}
}

func TestCheck_StaleBlockIsReported(t *testing.T) {
	dir := testfixture.Copy(t, "widget")
	src := testfixture.Read(t, dir, "component.yaml")
	src = strings.Replace(src, "    - conformance.widget.reverted.v1\n", "    - conformance.widget.deleted.v1\n", 1)
	testfixture.Write(t, dir, "component.yaml", src)
	c := load(t, dir)
	g, _ := Generate(c)
	d := Check(c, g)
	if len(d) != 2 || !strings.Contains(strings.Join(d, "\n"), "conformance.widget.reverted.v1") ||
		!strings.Contains(strings.Join(d, "\n"), "conformance.widget.deleted.v1") {
		t.Errorf("want missing reverted and extra deleted, got %v", d)
	}
}

func TestApply_WritesBlockThenCheckIsGreen(t *testing.T) {
	dir := testfixture.Copy(t, "widget")
	src := testfixture.Read(t, dir, "component.yaml")
	cut := strings.Index(src, "# Generated by be-ops")
	testfixture.Write(t, dir, "component.yaml", src[:cut])
	c := load(t, dir)
	g, _ := Generate(c)
	if len(Check(c, g)) == 0 {
		t.Fatal("seen red first: a missing block must be reported")
	}
	out := Apply(c.ManifestRaw, g)
	testfixture.Write(t, dir, "component.yaml", string(out))
	c2 := load(t, dir)
	if d := Check(c2, g); len(d) != 0 {
		t.Errorf("after apply: %v\n%s", d, out)
	}
	if again := Apply(out, g); string(again) != string(out) {
		t.Error("apply is not idempotent")
	}
}

func TestGenerate_SignalsAreNotDeclaredAndBadSubjectsRefused(t *testing.T) {
	dir := testfixture.Copy(t, "peer")
	testfixture.Write(t, dir, "contracts/events/x.events.json", `{"events":[
	  {"subject":"conformance.peer.changed.v1","x-aggregate-type":"conformance.peer.x","x-signal":true,"payload":{"type":"object"}}]}`)
	g, err := Generate(load(t, dir))
	if err != nil {
		t.Fatal(err)
	}
	for _, s := range g.Publishes {
		if s == "conformance.peer.changed.v1" {
			t.Error("a poke must not be declared")
		}
	}
	testfixture.Write(t, dir, "contracts/events/x.events.json", `{"events":[{"subject":"peer.Bad-Subject.v1"}]}`)
	if _, err := Generate(load(t, dir)); err == nil {
		t.Error("an invalid subject must be refused")
	}
}

func TestGenerate_NoEventsMeansNoBlock(t *testing.T) {
	dir := testfixture.Copy(t, "peer")
	testfixture.Write(t, dir, "contracts/events/peer.events.json", `{"events":[]}`)
	c := load(t, dir)
	g, _ := Generate(c)
	out := string(Apply(c.ManifestRaw, g))
	if strings.Contains(out, "\nevents:") {
		t.Errorf("block should be removed:\n%s", out)
	}
}
